
export const datas = [
    {
      "userId": 1,
      "firstName": "Nattaya",
      "lastName": "Kamonrat",
      "username": "nattaya123",
      "email": "nattaya@example.com",
      "password": "password123",
      "streetNumber": "55/2",
      "city": "Chiang Mai",
      "postalCode": "50000",
      "state": "Chiang Mai",
      "country": "Thailand"
    },
    {
      "userId": 2,
      "firstName": "Surasak",
      "lastName": "Thongchai",
      "username": "sura.tch",
      "email": "surasak@example.com",
      "password": "mypassword456",
      "streetNumber": "44/1",
      "city": "Bangkok",
      "postalCode": "10310",
      "state": "Bangkok",
      "country": "Thailand"
    },
    {
      "userId": 3,
      "firstName": "Pimchanok",
      "lastName": "Sirisopa",
      "username": "pimmy_siri",
      "email": "pimchanok@example.com",
      "password": "abc12345",
      "streetNumber": "123/8",
      "city": "Khon Kaen",
      "postalCode": "40000",
      "state": "Khon Kaen",
      "country": "Thailand"
    },
    {
      "userId": 4,
      "firstName": "Anan",
      "lastName": "Yamato",
      "username": "anan_y",
      "email": "anan@example.com",
      "password": "anan7890",
      "streetNumber": "88/9",
      "city": "Nakhon Ratchasima",
      "postalCode": "30000",
      "state": "Nakhon Ratchasima",
      "country": "Thailand"
    },
    {
      "userId": 5,
      "firstName": "Kanyarat",
      "lastName": "Meechai",
      "username": "kanya_meech",
      "email": "kanyarat@example.com",
      "password": "kanyaSecure",
      "streetNumber": "75",
      "city": "Pattaya",
      "postalCode": "20150",
      "state": "Chonburi",
      "country": "Thailand"
    },
    {
      "userId": 6,
      "firstName": "Tanawat",
      "lastName": "Pongchai",
      "username": "tanawat.dev",
      "email": "tanawat@example.com",
      "password": "tana4321",
      "streetNumber": "66/7",
      "city": "Hat Yai",
      "postalCode": "90110",
      "state": "Songkhla",
      "country": "Thailand"
    },
    {
      "userId": 7,
      "firstName": "Sirinya",
      "lastName": "Rojanakul",
      "username": "sirinya_ro",
      "email": "sirinya@example.com",
      "password": "siri2025",
      "streetNumber": "90/12",
      "city": "Surat Thani",
      "postalCode": "84000",
      "state": "Surat Thani",
      "country": "Thailand"
    },
    {
      "userId": 8,
      "firstName": "Jirawat",
      "lastName": "Thanom",
      "username": "jirawatx",
      "email": "jirawat@example.com",
      "password": "jwtpass98",
      "streetNumber": "18/2",
      "city": "Phuket",
      "postalCode": "83000",
      "state": "Phuket",
      "country": "Thailand"
    }
  ]